apiVersion: v1
kind: Namespace
metadata:
  name: taskflow
  labels:
    app.kubernetes.io/managed-by: argocd
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  APP_ENV:   "production"
  LOG_LEVEL: "info"
  PORT:      "8000"
